name: á´…Éªêœ±á´„á´Ê€á´… Ê€á´‡ÊŸá´‡á´€êœ±á´‡ É´á´á´›Éªêœ°Éªá´‡Ê€

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Notification
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-title: "ğŸš€ É´á´‡á´¡ Ê€á´‡ÊŸá´‡á´€êœ±á´‡: ${{ github.event.release.tag_name }}"
          embed-url: "${{ github.event.release.html_url }}"
          embed-description: "${{ github.event.release.body }}"
          embed-color: 16777215 # Pure White
          username: "Doppelganger Bot"
